# Generated by Django 5.1 on 2024-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('cod_coordinador', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sueldo', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
