# Generated by Django 5.1.2 on 2024-11-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_app', '0002_coordinador_delete_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='cod_coordinador',
            new_name='codigo',
        ),
    ]
